Web/Models/Account/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models.Account
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Usuário")]
        public string UserName { get; set; }
        
        [Required]
        [Display(Name ="Senha")]
        [StringLength(100, MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Manter conectado")]
        public bool RememberMe { get; set; }
    }
}

Web/Models/Account/RegistrarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models.Account
{
	public class RegistrarViewModel
	{
        [Required]
        [Display(Name = "Usuário")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar senha")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
    }
}

Web/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Owin;
using Web.Models;
using Web.Models.Account;
using System.Net;
using Database.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Web.Controllers
{
    public class ContaController : Controller
    {

        //
        // GET: /Account/

        public ActionResult Index()
        {
            return RedirectToAction("Login");
        }

        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Registrar(RegistrarViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new Usuario()
                {
                    UserName = model.UserName,
                    Email = model.Email
                };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await UserManager.AddToRoleAsync(user.Id, "User");
                    await SignInAsync(user, isPersistent: false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    AddErrors(result);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }
        
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindAsync(model.UserName, model.Password);
                if (user != null)
                {
                    await SignInAsync(user, model.RememberMe);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Usuário ou senha inválido.");
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }
        
        // POST: /Account/LogOff
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            AuthenticationManager.SignOut();
            return RedirectToAction("Index", "Home");
        }
        
    }
}

Web/Views/Conta/Login.cshtml
@model Web.Models.Account.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<div class="login">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text">
            <h1><strong>Página de Login</strong></h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3 form-box">
            <div class="form-top">
                <div class="form-top-left">
                    <h3>Login pela página SOS FEEVALE</h3>
                    <p>Insira seu usuário e senha:</p>
                </div>
                <div class="form-top-right">
                    <i class="fa fa-key"></i>
                </div>
            </div>
            <div class="form-bottom">
                @*<form role="form" action="" method="post" class="login-form">
                    <div class="form-group">
                        <label class="sr-only" for="form-username">Username</label>
                        <input type="text" name="form-username" placeholder="Email" class="form-username form-control" id="form-username">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" for="form-password">Password</label>
                        <input type="password" name="form-password" placeholder="Senha" class="form-password form-control" id="form-password">
                        <div style="float:right; font-size: 80%; position: relative; top:7px"><a href="#">Esqueceu a senha?</a></div>
                    </div>
                    <button type="submit" class="btn">Login!</button>

                </form>*@
                @using (Html.BeginForm("Login", "Conta", FormMethod.Post,new { @class = "login-form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.UserName)*@
                        @Html.TextBoxFor(model => model.UserName, new { @class = "form-control", placeholder = "Usuário" })
                        @Html.ValidationMessageFor(model => model.UserName)
                    </div>
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Password)*@
                        @Html.PasswordFor(model => model.Password, new { @class = "form-control", placeholder = Html.DisplayNameFor(n => n.Password) })
                        @Html.ValidationMessageFor(model => model.Password)
                    </div>
                    @Html.ValidationSummary("", new { @class = "text-danger" })

                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Logar" />
                    </div>
                }
            </div>
            <div class="form-group">
                <div class="col-md-12 control">
                    <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%">
                        Não tem uma conta!
                        @Html.ActionLink("Crie uma agora", "Registrar").
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/Conta/Registrar.cshtml
@model Web.Models.Account.RegistrarViewModel

<h2>Registrar usuário</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(model => model.UserName)
        @Html.TextBoxFor(model => model.UserName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.UserName)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email)
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Email)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Password)
        @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Password)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmPassword)
        @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ConfirmPassword)
    </div>
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Registrar" />
    </div>
}