Web/Models/Account/RegistrarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models.Account
{
	public class RegistrarViewModel
	{
        [Required]
        [Display(Name = "Usuário")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar senha")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
    }
}

Web/Models/Estabelecimento/IndexModelView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Database.Models;

namespace Web.Models.Estabelecimento
{
    public class IndexModelView
    {
        public Database.Models.Estabelecimento[] Estabelecimentos { get; internal set; }
        [Display(Name = "Pesquisar Estabelecimento:")]
        public string Pesquisa { get; set; }
    }
}

Web/Controllers/EstabelecimentoController.cs
using Database.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Models.Estabelecimento;

namespace Web.Controllers
{
    public class EstabelecimentoController : Controller
    {
        // GET: Estabelecimeto
        public ActionResult Index(IndexModelView model)
        {
            if (!string.IsNullOrEmpty(model.Pesquisa))
            {
                model.Estabelecimentos = db.Estabelecimento
                    .Where(p => p.Nome.Contains(model.Pesquisa) || p.Descricao.Contains(model.Pesquisa))
                    .ToArray();
            }
            else
            {
                model.Estabelecimentos = db.Estabelecimento.ToArray();
            }

            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Detalhe(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estabelecimento estabelecimento = db.Estabelecimento.Find(id);
            if (estabelecimento == null)
            {
                return HttpNotFound();
            }
            ViewBag.Produtos = estabelecimento.Produtos;
            return View(estabelecimento);
        }

        [Authorize]
        public ActionResult Registrar()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar([Bind(Include = "IdEstabelecimento,Nome,Descricao,Foto,Localizacao")] Estabelecimento estabelecimento)
        {
            if (ModelState.IsValid)
            {
                db.Estabelecimento.Add(estabelecimento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(estabelecimento);
        }

        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Deletar(int? idEstabelecimento)
        {
            if (idEstabelecimento == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estabelecimento estabelecimento = db.Estabelecimento.Find(idEstabelecimento);
            if (estabelecimento == null)
            {
                return HttpNotFound();
            }
            db.Estabelecimento.Remove(estabelecimento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Web/Controllers/ProdutoController.cs
using Database.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Models.Produto;

namespace Web.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: Produtos
        public ActionResult Index(IndexModelView model)
        {
            if (!string.IsNullOrEmpty(model.Pesquisa))
            {
                model.Produtos= db.Produto
                    .Where(p => p.Nome.Contains(model.Pesquisa) || p.Descricao.Contains(model.Pesquisa) || p.TipoProduto.Descricao.Contains(model.Pesquisa))
                    .ToArray();
            } else
            {
                model.Produtos = db.Produto.ToArray();
            }

            return View(model);
        }

        public ActionResult Detalhe(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produto.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            ViewBag.TipoProduto = produto.TipoProduto.Descricao;
            return View(produto);
        }

        [Authorize]
        public ActionResult Registrar()
        {
            ViewBag.IdEstabelecimento = new SelectList(db.Estabelecimento, "IdEstabelecimento", "Nome");
            ViewBag.IdTipoProduto = new SelectList(db.TipoProduto, "IdTipoProduto", "Descricao");
            return View();
        }

        // POST: EstabelecimentoTeste/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar([Bind(Include = "IdProduto,Nome,Descricao,Preco,Foto,Ativo,IdTipoProduto,IdEstabelecimento")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Produto.Add(produto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdEstabelecimento = new SelectList(db.Estabelecimento, "IdEstabelecimento", "Nome");
            ViewBag.IdTipoProduto = new SelectList(db.TipoProduto, "IdTipoProduto", "Descricao");
            return View(produto);
        }

        [Authorize]
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produto.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdEstabelecimento = new SelectList(db.Estabelecimento, "IdEstabelecimento", "Nome", produto.IdEstabelecimento);
            ViewBag.IdTipoProduto = new SelectList(db.TipoProduto, "IdTipoProduto", "Descricao", produto.IdTipoProduto);
            return View(produto);
        }

        // POST: EstabelecimentoTeste/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "IdProduto,Nome,Descricao,Preco,Foto,Ativo,IdTipoProduto,IdEstabelecimento")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdEstabelecimento = new SelectList(db.Estabelecimento, "IdEstabelecimento", "Nome", produto.IdEstabelecimento);
            ViewBag.IdTipoProduto = new SelectList(db.TipoProduto, "IdTipoProduto", "Descricao", produto.IdTipoProduto);
            return View(produto);
        }

        // POST: Produtoes/Delete/5
        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Deletar(int? idProduto)
        {
            if (idProduto == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produto.Find(idProduto);
            if (produto == null)
            {
                return HttpNotFound();
            }
            db.Produto.Remove(produto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Web/Views/Estabelecimento/Detalhe.cshtml
@using Database.Models;
@model Estabelecimento

@{
    ViewBag.Title = "Detalhe";
    IEnumerable<Produto> produtos = ViewBag.Produtos;
}

<h2>Detalhe</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4>@Model.Nome</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-8">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Descricao)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Descricao)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Localizacao)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Localizacao)
                    </dd>
                </dl>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-4">
                @Html.Image(Model.Foto)
            </div>
        </div>
    </div>
</div>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    using (Html.BeginForm("Deletar", "Estabelecimento"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.IdEstabelecimento)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
}

@if (produtos != null && produtos.Count() > 0)
{
    <h2>Produtos</h2>

    <div class="row">
        @for (int i = 0; i < produtos.Count(); i++)
        {
            var produto = produtos.ElementAt(i);

            <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="thumbnail">
                    @Html.Image(produto.Foto)
                    <div class="caption">
                        <h3>@produto.Nome</h3>
                        <p>@produto.Descricao</p>
                        <p>@string.Format("{0:C}", produto.Preco)</p>
                        <p>
                            @Html.ActionLink("Abrir", "Detalhe", "Produto", new { id = produto.IdProduto }, new { @class = "btn btn-primary" })
                        </p>
                    </div>
                </div>
            </div>

            if (i > 1)
            {
                if (((i + 1) % 3) == 0)
                {
                    <div class="clearfix visible-lg-block"></div>
                }
                if (((i + 1) % 2) == 0)
                {
                    <div class="clearfix visible-md-block"></div>
                }
                <div class="clearfix visible-sm-block"></div>
            }
        }
    </div>
}

Web/Views/Estabelecimento/Index.cshtml
@model Web.Models.Estabelecimento.IndexModelView

@{
    ViewBag.Title = "Index";
}

<h2>Estabelecimentos</h2>

<div class="panel panel-default">
    <div class="panel-body">
        @using (Html.BeginForm("Index", "Estabelecimento", FormMethod.Post, new { @class = "form-inline" }))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Pesquisa)
                @Html.TextBoxFor(model => model.Pesquisa, new { @class = "form-control" })
            </div>
            <a class="btn btn-default pull-right" href="@Url.Action("Registrar")">
                Adicionar
                <i class="glyphicon glyphicon-plus"></i>
            </a>
        }
    </div>

</div>

<div class="row">
    @for (int i = 0; i < Model.Estabelecimentos.Count(); i++)
    {
        var estabelecimento = Model.Estabelecimentos.ElementAt(i);

        <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="thumbnail">
                <img src="" alt="">
                @Html.Image(estabelecimento.Foto)
                <div class="caption">
                    <h3>@estabelecimento.Nome</h3>
                    <p>@estabelecimento.Descricao</p>
                    <p>
                        @Html.ActionLink("Abrir", "Detalhe", new { id = estabelecimento.IdEstabelecimento }, new { @class = "btn btn-primary" })
                    </p>
                </div>
            </div>
        </div>

        if (i > 1)
        {
            if (((i + 1) % 3) == 0)
            {
                <div class="clearfix visible-lg-block"></div>
            }
            if (((i + 1) % 2) == 0)
            {
                <div class="clearfix visible-md-block"></div>
            }
            <div class="clearfix visible-sm-block"></div>
        }
    }
</div>

Web/Views/Estabelecimento/Registrar.cshtml
@model Database.Models.Estabelecimento

@{
    ViewBag.Title = "Registrar";
}


<h2>Resgistrar Estabelecimento</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Nome)
        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Nome)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descricao)
        @Html.TextBoxFor(model => model.Descricao, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Descricao)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Localizacao)
        @Html.TextBoxFor(model => model.Localizacao, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Localizacao)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Foto)
        @Html.TextBoxFor(model => model.Foto, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Foto)
    </div>

    <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Resgistrar" />
    </div>
}